### ISSUE TITLE
Add Google Authenticator Support 

### ISSUE THREAD

**Issue by 0x46616c6b** [systemli/ansible-role-sshd#1]
```
- name: ensure google authenticator pam module is installed
  apt:
    pkg: libpam-google-authenticator
    state: installed

- name: ensure authenticator is loaded
  lineinfile:
    dest: /etc/pam.d/sshd
    insertafter: "# PAM configuration for the Secure Shell service"
    line: "auth required pam_google_authenticator.so"
    state: present
    backup: true
  notify: restart ssh
```

should only works on jessie or newer releases. requires 

```
sshd_challenge_response_authentication: "yes"
sshd_password_authentication: "yes"
```
